name: Backend CI/CD
on:
   push:
     branches: [main]
     paths: ['server/**'] # only when backend code changes
jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4 # get your code
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKERHUB_TOKEN }}" |
           docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
       - name: Build the image
         run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-server:latest ./server
       - name: Push the image
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-server:latest
