name: GitHub Actions Demo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  echo-vars-and-secrets:
    name: 1 - Echo variables and secrets
    runs-on: ubuntu-latest

    environment: development

    env:
      MY_VARIABLE: ${{ vars.MY_VARIABLE }}
      MY_SECRET: ${{ secrets.MY_SECRET }}

    steps:
      - name: Echo repository variable
        run: echo "$MY_VARIABLE"

      - name: Echo repository secret
        run: echo "$MY_SECRET"

      - name: Echo built-in GITHUB_TOKEN secret
        run: echo "GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}"

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: List files in repository
        run: |
          ls ${{ github.workspace }}

      - name: Show job status
        run: echo "🍏 Job status is ${{ job.status }}"